"""Write a small, committed candle file so `backtest` can be run by a reader.

Why a generator and not just a checked-in file
----------------------------------------------
A CSV of prices with no stated provenance is a liability in a trading repository: someone will
eventually treat it as real US30 data. So the file is small, it is committed under
``tests/fixtures/`` rather than ``data/``, and the script that made it is committed beside it
with its seed. Anyone can regenerate the identical file and anyone can see it was invented.

The series is random with trends *and* reversals, because a stop-and-target system tested only
on a straight line never exercises the half of its logic that matters. The seed is fixed, so the
file is identical on every machine.
"""

from __future__ import annotations

import argparse
import random
from datetime import UTC, datetime, timedelta
from decimal import Decimal
from pathlib import Path

#: Fixed so the committed file is reproducible. Changing it changes the fixture, and any test
#: asserting a number from it must be updated at the same time.
SEED = 20260312
BARS = 1440  # a full day of M1
#: How many bars a trend or reversal runs for before the regime flips.
#:
#: Tuned, and the tuning is the interesting part. A per-bar random walk produces *zero* trades
#: on this rule: the M15 direction filter correctly rejects a series with no direction, and a
#: fixture that reports an empty result teaches a reader nothing about whether the command
#: works. Thirty-bar regimes produce 15 trades but a negative result; ninety produce 9 trades
#: and an implausibly good one. Forty-five gives 19 trades, 9 winners and 10 losers, and hits
#: both the trailing stop and the take profit -- so the sample exercises every exit path and
#: its win rate is below 50%, which is what makes it credible rather than flattering.
REGIME_BARS = 45
START = datetime(2026, 3, 12, 0, 0, tzinfo=UTC)
DEFAULT_OUT = Path("tests/fixtures/us30_m1_sample.csv")


def build(bars: int = BARS, seed: int = SEED, regime_bars: int = REGIME_BARS) -> list[tuple]:
    rng = random.Random(seed)
    price = Decimal("40150.0")
    rows: list[tuple[datetime, ...]] = []
    direction = 1
    for index in range(bars):
        if index % regime_bars == 0:
            direction = rng.choice([1, 1, -1, -1, 1, -1])
        drift = Decimal(direction) * Decimal(str(round(rng.uniform(0.15, 0.6), 3)))
        noise = Decimal(str(round(rng.uniform(-0.35, 0.35), 3)))
        open_ = price
        close = open_ + drift + noise
        high = max(open_, close) + Decimal(str(round(rng.uniform(0.1, 0.8), 3)))
        low = min(open_, close) - Decimal(str(round(rng.uniform(0.1, 0.8), 3)))
        quantise = Decimal("0.1")
        rows.append(
            (
                START + timedelta(minutes=index),
                open_.quantize(quantise),
                high.quantize(quantise),
                low.quantize(quantise),
                close.quantize(quantise),
            )
        )
        price = close
    return rows


def render(rows: list[tuple[datetime, ...]]) -> str:
    lines = [
        "# SYNTHETIC sample data. Not real US30 prices, and not evidence about a market.",
        "# Generated by scripts/make_sample_candles.py with seed "
        f"{SEED}; regenerate to reproduce this file exactly.",
        "time,open,high,low,close",
    ]
    for moment, open_, high, low, close in rows:
        lines.append(
            f"{moment.strftime('%Y-%m-%dT%H:%M:%SZ')},{open_},{high},{low},{close}"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--bars", type=int, default=BARS)
    parser.add_argument("--seed", type=int, default=SEED)
    parser.add_argument("--regime-bars", type=int, default=REGIME_BARS)
    args = parser.parse_args()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        render(build(args.bars, args.seed, args.regime_bars)), encoding="utf-8"
    )
    print(f"wrote {args.out} ({args.bars} bars, seed {args.seed}, regime {args.regime_bars})")


if __name__ == "__main__":
    main()
